include:
  - https://cnb.cool/otw1248/public/template/templateforcnb/-/blob/main/runtime-cnbdev.yml

main:
  push:
    services: 
      stages:
        - name: sync to github
          image: tencentcom/git-sync
          imports: https://cnb.cool/otw1248/secret/-/blob/main/github.yml
          timeout: 1h
          settings:
            target_url: "https://github.com/otw128/toolsfromai.git"
            auth_type: "https" # 或 "https"
            #ssh_key: "${SSH_KEY}" # 如果使用 SSH
            username: "${GITHUB_UN_2}" # 如果使用 HTTPS
            password: "${syncCodeForOTW128}" # 如果使用 HTTPS
            branch: "main" # 可选，指定要推送的分支
            force: true # 可选，是否强制推送
            push_tags: true # 可选，是否推送标签
            git_user: "${GITHUB_UN_2}" # 可选，设置 git user.name
            git_email: "${GITHUB_EMAIL_ADDR}" # 可选，设置 git user.email
            #git_host: "git.example.com" # 可选，如果使用自定义 Git 服务器
        - name: send msg to feishu
          imports: https://cnb.cool/otw1248/secret/-/blob/main/feishu.yml
          image: tencentcom/feishu-message
          settings:
            robot: $msgFromCnbForMsgs
            content: $sendingMsgToFeishuKeys - ${CNB_REPO_SLUG_LOWERCASE} succeed to sync repo from cnb to other platforms(github)!
        - name: send msg to wecome
          imports: https://cnb.cool/otw1248/secret/-/blob/main/wecom.yml
          image: tencentcom/wecom-message
          settings:
            robot: $wecom_cnb_robot_msg
            content: $wecom_cnb_robot_msgKeys - ${CNB_REPO_SLUG_LOWERCASE} succeed to sync repo from cnb to other platforms(github)!              
      failStages:
        - name: send msg to feishu
          imports: https://cnb.cool/otw1248/secret/-/blob/main/feishu.yml
          image: tencentcom/feishu-message
          settings:
            robot: $msgFromCnbForMsgs
            content: $sendingMsgToFeishuKeys - ${CNB_REPO_SLUG_LOWERCASE} failed to sync repo from cnb to other platforms(github)!!!
        - name: send msg to wecome
          imports: https://cnb.cool/otw1248/secret/-/blob/main/wecom.yml
          image: tencentcom/wecom-message
          settings:
            robot: $wecom_cnb_robot_msg
            content: $wecom_cnb_robot_msgKeys - ${CNB_REPO_SLUG_LOWERCASE} failed to sync repo from cnb to other platforms(github)!!!   